const { Router } = require('express');
const router = Router();
const fs = require('fs');

const students = [
    {id: 1, name: 'John', age: 21, enroll: true },
    {id: 2, name: 'Juana', age: 31, enroll: false },
    {id: 3, name: 'Foxi', age: 51, enroll: true, ggg: 'dfdf' },
    {
        id: 4,
        idtofertastandar: 11394,
        idtoferta: 9727,
        idtstandar: 5,
        desstandar: null,
        idttiponace: 71,
        idttipoacreditacion: 6,
        destipoacreditacion: null,
        idttipoauditoria: 1,
        idttipootraacreditacion: null,
        idtmoduloevaluacion: null,
        subtotal: 1500,
        totaligv: 270,
        total: 1770,
        idtauditor: null,
        codigovalidez: "QS-PER/GRD/0823/N4484",
        codigovalidezi: "QS-PER*GRD*0823*N4484",
        idtfirma: 2,
        file_informe: "",
        file_certificado: "",
        flaestado: 1,
        mce_coOferta: null,
        mce_coStandar: null,
        mce_coTipoNace: null,
        mce_coTipoAcreditacion: null,
        mce_coTipoAuditoria: null,
        mce_coFirma: null,
        mcl_coTipoNace: null,
        mcl_coOfertaStandarNace: null,
        mcl_coOfertaStandarPregunta: null,
        mcl_coTipoAcreditacionStandar: null,
        mcl_coTipoAuditoria: null,
        mcl_coModuloEvaluacion: null
        },

        {
            id: 5,
            idtofertastandar: 11395,
            idtoferta: 9727,
            idtstandar: 5,
            desstandar: null,
            idttiponace: 71,
            idttipoacreditacion: 6,
            destipoacreditacion: null,
            idttipoauditoria: 1,
            idttipootraacreditacion: null,
            idtmoduloevaluacion: null,
            subtotal: 1500,
            totaligv: 270,
            total: 1770,
            idtauditor: null,
            codigovalidez: "QS-PER/GRD/0823/N4485",
            codigovalidezi: "QS-PER*GRD*0823*N4484",
            idtfirma: 2,
            file_informe: "",
            file_certificado: "",
            flaestado: 1,
            mce_coOferta: null,
            mce_coStandar: null,
            mce_coTipoNace: null,
            mce_coTipoAcreditacion: null,
            mce_coTipoAuditoria: null,
            mce_coFirma: null,
            mcl_coTipoNace: null,
            mcl_coOfertaStandarNace: null,
            mcl_coOfertaStandarPregunta: null,
            mcl_coTipoAcreditacionStandar: null,
            mcl_coTipoAuditoria: null,
            mcl_coModuloEvaluacion: null
            }
];



const certificado = [
    {
      idtofertastandar: 11394,
      idtoferta: 9727,
      idtstandar: 5,
      desstandar: null,
      idttiponace: 71,
      idttipoacreditacion: 6,
      destipoacreditacion: null,
      idttipoauditoria: 1,
      idttipootraacreditacion: null,
      idtmoduloevaluacion: null,
      subtotal: 1500,
      totaligv: 270,
      total: 1770,
      idtauditor: null,
      codigovalidez: "QS-PER/GRD/0823/N4484",
      idtfirma: 2,
      file_informe: "",
      file_certificado: "",
      flaestado: 5,
      mce_coOferta: {
        idtoferta: 9727,
        idtperiodo: 4,
        idtpartner: 6,
        idtcliente: 7260,
        idttiposervicio: 1,
        fecemision: "2023/07/17",
        numero: "2023-7040",
        registro: "FX-XXX",
        numero_empleados: 0,
        numero_ubicaciones_afuera_ho: 0,
        numero_turnos: 0,
        actividad: "",
        actividad_ingles: "",
        numero_sucursales_auditadas: 0,
        tarifa_inicial: 0,
        tarifa_inicial_dias: 0,
        tarifa_inicial_precio: 4500,
        tarifa_seguimiento_1: 0,
        tarifa_seguimiento_1_dias: 0,
        tarifa_seguimiento_1_precio: 2500,
        tarifa_seguimiento_2: 0,
        tarifa_seguimiento_2_dias: 0,
        tarifa_seguimiento_2_precio: 2500,
        costo_viaje: 0,
        costo_alojamiento: 0,
        tarifa_extraordinaria_auditoria: 0,
        tarifa_extraordinaria_auditoria_remota: 0,
        otros_costos: 0,
        fob: 0,
        fob_porcentaje: 0,
        idttipomoneda: 1,
        flamostrar_dias_auditoria: 0,
        flacontrato_firmado: 0,
        flafacturar: 0,
        correoejecutivo: null,
        correocliente: null,
        flaadjuntar_brochure: 0,
        flaadjuntar_proforma: 0,
        flaadjuntar_cartainacal: 0,
        flaadjuntar_acreditacion: 0,
        flaadjuntar_cuentacorriente: 0,
        file_contrato: "9727-CN.pdf",
        file_contrato_flaestado: 0,
        file_contrato_observacion: null,
        file_condiciones: "9727-TC.pdf",
        file_condiciones_flaestado: 0,
        file_condiciones_observacion: null,
        solicitud_alcance: null,
        solicitud_alcance_flaestado: 0,
        solicitud_alcance_observacion: null,
        flacontinuidadnegocio: 0,
        file_continuidadnegocio_flaestado: 0,
        file_continuidadnegocio_observacion: null,
        flarnp: 0,
        file_rnp: null,
        file_rnp_flaestado: 0,
        file_rnp_observacion: null,
        flabacklog: 0,
        file_backlog: null,
        file_backlog_flaestado: 0,
        file_backlog_observacion: null,
        fechasolicitudservicio: null,
        fechaaprobacionservicio: null,
        fechaservicioinicio: null,
        fechaserviciotermino: null,
        fechaentrega: null,
        fechacertificacion: null,
        flasistemagestion: 0,
        flapartner: 0,
        flafacturarapartner: 0,
        flafacturaratercero: 0,
        facturaratercero_idtcliente: null,
        flaestado: 5,
        idtprioridad: null,
        idtauditor: null,
        dias_auditoria: 3,
        alcance: "CONSULTORÍA EN ELABORACIÓN DE EXPEDIENTES TÉCNICOS, SUPERVISIÓN Y EJECUCIÓN DE OBRAS DE INGENIERÍA: CONSTRUCCIÓN Y/O CREACIÓN Y/O INSTALACIÓN Y/O AMPLIACIÓN Y/O MEJORAMIENTO Y/O RECONSTRUCCIÓN Y/O REHABILITACIÓN Y/O REPARACIÓN Y/O RENOVACIÓN Y/O RECUPERACIÓN Y/O ACONDICIONAMIENTO Y/O REMODELACIÓN Y/O RECONSTRUCCIÓN  Y/O IMPLEMENTACIÓN Y/O MANTENIMIENTO EN: SANEAMIENTO , EQUIPAMIENTO, ESCUELAS, COLEGIOS , INSTITUTOS , UNIVERSIDADES, AULAS , PABELLONES, LOSAS DEPORTIVAS, MULTIDEPORTIVAS, POSTAS MEDICAS, CENTROS DE SALUD; INFRAESTRUCTURAS ELÉCTRICAS, ELECTROMECÁNICAS , MECÁNICAS; PISTAS, VEREDAS , ÁREAS VERDES , SARDINELES, FACHADAS, PASAJES, CALLES, CARRETERAS, PAVIMENTO FLEXIBLE O RÍGIDO EN ZONAS URBANAS Y RURALES, CICLOVÍAS, TROCHAS CARROZABLES, VÍAS, SERVICIO DE TRANSITABILIDAD VEHICULAR Y PEATONAL, CARRETERAS VECINALES, CAMINOS VECINALES , CANALES DE CONCRETO Y DE RIEGO, DEFENSAS RIBEREÑAS, DIQUES, PROTECCIÓN DE INFRAESTRUCTURA BÁSICA, HIDRÁULICAS E IRRIGACIÓN, AGUA POTABLE Y ALCANTARILLADO, LETRINAS, CONEXIONES DOMICILIARIAS DE AGUA Y DESAGÜE, POZOS, REPRESAS, HOSPITALES, CANALES DE IRRIGACIÓN, FORESTACIÓN, PUENTES, ELECTRIFICACIÓN, CENTRALES HIDROELÉCTRICAS.",
        alcance_ingles: "CONSULTING IN THE PREPARATION OF TECHNICAL FILES, SUPERVISION AND EXECUTION OF ENGINEERING WORKS: CONSTRUCTION AND/OR CREATION AND/OR INSTALLATION AND/OR EXTENSION AND/OR IMPROVEMENT AND/OR RECONSTRUCTION AND/OR REHABILITATION AND/OR REPAIR AND/OR RENEWAL AND/ O RECOVERY AND/OR CONDITIONING AND/OR REMODELING AND/OR RECONSTRUCTION AND/OR IMPLEMENTATION AND/OR MAINTENANCE IN: SANITATION, EQUIPMENT, SCHOOLS, SCHOOLS, INSTITUTES, UNIVERSITIES, CLASSROOMS, PAVILIONS, SPORTS SITES, MULTI-SPORTS SITES, MEDICAL CENTERS, CENTERS HEALTH; ELECTRICAL, ELECTROMECHANICAL, MECHANICAL INFRASTRUCTURES; TRACKS, SIDEWALKS, GREEN AREAS, SARDINELS, FACADES, PASSAGES, STREETS, HIGHWAYS, FLEXIBLE OR RIGID PAVEMENT IN URBAN AND RURAL AREAS, CYCLE PATHS, TRAILS FOR CARS, ROADS, VEHICULAR AND PEDESTRIAN TRANSIT SERVICE, NEIGHBORHOOD ROADS, NEIGHBORHOOD ROADS, CONCRETE CHANNELS AND IRRIGATION, RIVER DEFENSES, DIKES, PROTECTION OF BASIC INFRASTRUCTURE, HYDRAULIC AND IRRIGATION, DRINKING WATER AND SEWERAGE, LATRINES, HOUSEHOLD WATER AND SEWAGE CONNECTIONS, WELLS, DAMS, HOSPITALS, IRRIGATION CANALS, FORESTATION, BRIDGES, ELECTRIFICATION, HYDROELECTRIC POWER PLANTS .",
        direccion: "CALLE ALICANTE 213, URB. JAVIER PRADO 5 TA ETAPA",
        direccion_ciudad: "LIMA - LIMA - SAN LUIS",
        direccion_pais: "PERÚ",
        file_logo: "",
        idtemitirfacturaa: 1,
        codigovalidez: null,
        fecvalidezdesde: "2023/08/02",
        fecvalidezhasta: "2026/07/02",
        fecprimeraexpedicion: "2024/07/02",
        fecsegundaexpedicion: "2025/07/02",
        fecsegundafechavigilancia: null,
        fecrecertificacionvence: null,
        fecproblemainicial: null,
        fecasunto: null,
        feccaducidad: null,
        idtfirma: null,
        cliente_fontsize: 17,
        clientedireccion_fontsize: 10,
        alcance_fontsize: 8,
        tracking_direccion: null,
        tracking_contacto: null,
        tracking_telefono: null,
        tracking_referencia: null,
        tracking_numero: null,
        flaestadoplaneacion: 5,
        cobranza_abono: 0,
        cobranza_saldo: 0,
        flaestadocobranza: 0,
        file_informe1: "",
        informe_observacion1: "",
        informe_respuesta1: "",
        file_informe2: "",
        informe_observacion2: "",
        informe_respuesta2: "",
        flaestadoauditoria: 1,
        file_diseno1: null,
        file_diseno2: null,
        certificado_email: null,
        certificado_flaestado: 1,
        certificado_flasuspender: 0,
        usuregistro: null,
        fecregistro: null,
        usumodifica: null,
        fecmodifica: "2023-08-15T21:32:51.427",
        mce_ctPartner: {
          "idtpartner": 0,
          "idtsucursal": 0,
          "despartner": "SISTEMACERTS /Diomedes Maza",
          "email": "diomedes.maza@ll-c.pe",
          "idttipoidentidad": null,
          "nombrecompleto": null,
          "numeroidentificacionfiscal": null,
          "direccion": null,
          "idtubigeo": 0,
          "flaestado": 0,
          "usuregistro": null,
          "fecregistro": null,
          "usumodifica": null,
          "fecmodifica": null,
          "mce_geUbigeo": null
        },
        "mce_coCliente": {
          "idtcliente": 0,
          "idtpartner": 0,
          "nombrecompleto": "E & E INGENIEROS CONSULT S.A.C",
          "nombrecompletoingles": null,
          "nombre": null,
          "numeroregistro": null,
          "numeroidentificacionfiscal": "20494101662",
          "web": null,
          "calle": "AL.ALICANTE NRO. 213 URB. JAVIER PRADO 5TA ETAPA LIMA - LIMA - SAN LUIS",
          "calleingles": null,
          "ciudad": "",
          "codigopostal": null,
          "ciudadingles": null,
          "idtubigeo": null,
          "pais": null,
          "contacto": null,
          "email": null,
          "telefono1": null,
          "telefono2": null,
          "telefono3": null,
          "representantelegal": null,
          "posicioncontacto": null,
          "emailcontacto": null,
          "logo": null,
          "flaproforma": 0,
          "flaestado": 0,
          "usuregistro": null,
          "fecregistro": "0001-01-01T00:00:00",
          "usumodifica": null,
          "fecmodifica": null,
          "mce_ctPartner": null,
          "mce_geTipoIdentidad": null,
          "mce_geUbigeo": null
        },
        "mce_coTipoServicio": null,
        "mce_geTipoMoneda": {
          "idttipomoneda": 0,
          "destipomoneda": "PEN",
          "abreviatura": null,
          "sunat": null,
          "flaestado": 0,
          "usuregistro": null,
          "fecregistro": null,
          "usumodifica": null,
          "fecmodifica": null
        },
        "mce_ctUsuario": null,
        "mce_coAuditor": null,
        "mce_coFirma": null,
        "mcl_coOfertaStandar": null,
        "mcl_coOfertaDiasAuditorias": null,
        "mcl_coOfertaRequisitoDetalle": null,
        "mcl_coOfertaPago": null,
        "mcl_coOfertaPago_Detraccion": null,
        "searchIdtstandar": 0,
        "searchMes": 0,
        "searchPeriodo": 0,
        "searchIdttipoauditoria": 0,
        "searchEjecutivoComercial": 0,
        "searchDepartamento": null,
        "standars": null,
        "tiposervicios": null
      },
      "mce_coStandar": {
        "idtstandar": 0,
        "idttiponacegrupo": 0,
        "desstandar": "ISO 45001:2018",
        "descripcion": "Sistema de Gestión de la Seguridad y la Salud en el Trabajo",
        "descripcionen": "Occupational Health and Safety Management  System ",
        "reconocimientointernacional": "IAF Forum Internacional de Acreditacion https://www.iaf.nu",
        "flaorderby": 0,
        "flaestado": 0,
        "usuregistro": null,
        "fecregistro": null,
        "usumodifica": null,
        "fecmodifica": null
      },
      "mce_coTipoNace": {
        "idttiponace": 0,
        "codigo": "42",
        "idttiponacegrupo": 0,
        "destiponace": null,
        "flaestado": 0,
        "usuregistro": null,
        "fecregistro": null,
        "usumodifica": null,
        "fecmodifica": null,
        "mce_coStandar": null
      },
      "mce_coTipoAcreditacion": {
        "idttipoacreditacion": 0,
        "destipoacreditacion": "IAS",
        "flaestado": 0,
        "usuregistro": null,
        "fecregistro": null,
        "usumodifica": null,
        "fecmodifica": null
      },
      "mce_coTipoAuditoria": {
        "idttipoauditoria": 0,
        "destipoauditoria": "Auditoria Certificacion Inicial",
        "flaestado": 0,
        "usuregistro": null,
        "fecregistro": null,
        "usumodifica": null,
        "fecmodifica": null
      },
      "mce_coFirma": {
        "idtfirma": 0,
        "desfirma": null,
        "archivo": "certificado-firma-aprobado-1p.png",
        "flaestado": 0,
        "usuregistro": null,
        "fecregistro": null,
        "usumodifica": null,
        "fecmodifica": null
      },
      "mcl_coTipoNace": null,
      "mcl_coOfertaStandarNace": null,
      "mcl_coOfertaStandarPregunta": null,
      "mcl_coTipoAcreditacionStandar": null,
      "mcl_coTipoAuditoria": null,
      "mcl_coModuloEvaluacion": null
    },


    {
        idtofertastandar: 11395,
        idtoferta: 9727,
        idtstandar: 5,
        desstandar: null,
        idttiponace: 71,
        idttipoacreditacion: 6,
        destipoacreditacion: null,
        idttipoauditoria: 1,
        idttipootraacreditacion: null,
        idtmoduloevaluacion: null,
        subtotal: 1500,
        totaligv: 270,
        total: 1770,
        idtauditor: null,
        codigovalidez: "QS-PER/GRD/0823/N4485",
        idtfirma: 2,
        file_informe: "",
        file_certificado: "",
        flaestado: 5,
        mce_coOferta: {
          idtoferta: 9727,
          idtperiodo: 4,
          idtpartner: 6,
          idtcliente: 7260,
          idttiposervicio: 1,
          fecemision: "2023/07/17",
          numero: "2023-7040",
          registro: "FX-XXX",
          numero_empleados: 0,
          numero_ubicaciones_afuera_ho: 0,
          numero_turnos: 0,
          actividad: "",
          actividad_ingles: "",
          numero_sucursales_auditadas: 0,
          tarifa_inicial: 0,
          tarifa_inicial_dias: 0,
          tarifa_inicial_precio: 4500,
          tarifa_seguimiento_1: 0,
          tarifa_seguimiento_1_dias: 0,
          tarifa_seguimiento_1_precio: 2500,
          tarifa_seguimiento_2: 0,
          tarifa_seguimiento_2_dias: 0,
          tarifa_seguimiento_2_precio: 2500,
          costo_viaje: 0,
          costo_alojamiento: 0,
          tarifa_extraordinaria_auditoria: 0,
          tarifa_extraordinaria_auditoria_remota: 0,
          otros_costos: 0,
          fob: 0,
          fob_porcentaje: 0,
          idttipomoneda: 1,
          flamostrar_dias_auditoria: 0,
          flacontrato_firmado: 0,
          flafacturar: 0,
          correoejecutivo: null,
          correocliente: null,
          flaadjuntar_brochure: 0,
          flaadjuntar_proforma: 0,
          flaadjuntar_cartainacal: 0,
          flaadjuntar_acreditacion: 0,
          flaadjuntar_cuentacorriente: 0,
          file_contrato: "9727-CN.pdf",
          file_contrato_flaestado: 0,
          file_contrato_observacion: null,
          file_condiciones: "9727-TC.pdf",
          file_condiciones_flaestado: 0,
          file_condiciones_observacion: null,
          solicitud_alcance: null,
          solicitud_alcance_flaestado: 0,
          solicitud_alcance_observacion: null,
          flacontinuidadnegocio: 0,
          file_continuidadnegocio_flaestado: 0,
          file_continuidadnegocio_observacion: null,
          flarnp: 0,
          file_rnp: null,
          file_rnp_flaestado: 0,
          file_rnp_observacion: null,
          flabacklog: 0,
          file_backlog: null,
          file_backlog_flaestado: 0,
          file_backlog_observacion: null,
          fechasolicitudservicio: null,
          fechaaprobacionservicio: null,
          fechaservicioinicio: null,
          fechaserviciotermino: null,
          fechaentrega: null,
          fechacertificacion: null,
          flasistemagestion: 0,
          flapartner: 0,
          flafacturarapartner: 0,
          flafacturaratercero: 0,
          facturaratercero_idtcliente: null,
          flaestado: 5,
          idtprioridad: null,
          idtauditor: null,
          dias_auditoria: 3,
          alcance: "CONSULTORÍA EN ELABORACIÓN DE EXPEDIENTES TÉCNICOS, SUPERVISIÓN Y EJECUCIÓN DE OBRAS DE INGENIERÍA: CONSTRUCCIÓN Y/O CREACIÓN Y/O INSTALACIÓN Y/O AMPLIACIÓN Y/O MEJORAMIENTO Y/O RECONSTRUCCIÓN Y/O REHABILITACIÓN Y/O REPARACIÓN Y/O RENOVACIÓN Y/O RECUPERACIÓN Y/O ACONDICIONAMIENTO Y/O REMODELACIÓN Y/O RECONSTRUCCIÓN  Y/O IMPLEMENTACIÓN Y/O MANTENIMIENTO EN: SANEAMIENTO , EQUIPAMIENTO, ESCUELAS, COLEGIOS , INSTITUTOS , UNIVERSIDADES, AULAS , PABELLONES, LOSAS DEPORTIVAS, MULTIDEPORTIVAS, POSTAS MEDICAS, CENTROS DE SALUD; INFRAESTRUCTURAS ELÉCTRICAS, ELECTROMECÁNICAS , MECÁNICAS; PISTAS, VEREDAS , ÁREAS VERDES , SARDINELES, FACHADAS, PASAJES, CALLES, CARRETERAS, PAVIMENTO FLEXIBLE O RÍGIDO EN ZONAS URBANAS Y RURALES, CICLOVÍAS, TROCHAS CARROZABLES, VÍAS, SERVICIO DE TRANSITABILIDAD VEHICULAR Y PEATONAL, CARRETERAS VECINALES, CAMINOS VECINALES , CANALES DE CONCRETO Y DE RIEGO, DEFENSAS RIBEREÑAS, DIQUES, PROTECCIÓN DE INFRAESTRUCTURA BÁSICA, HIDRÁULICAS E IRRIGACIÓN, AGUA POTABLE Y ALCANTARILLADO, LETRINAS, CONEXIONES DOMICILIARIAS DE AGUA Y DESAGÜE, POZOS, REPRESAS, HOSPITALES, CANALES DE IRRIGACIÓN, FORESTACIÓN, PUENTES, ELECTRIFICACIÓN, CENTRALES HIDROELÉCTRICAS.",
          alcance_ingles: "CONSULTING IN THE PREPARATION OF TECHNICAL FILES, SUPERVISION AND EXECUTION OF ENGINEERING WORKS: CONSTRUCTION AND/OR CREATION AND/OR INSTALLATION AND/OR EXTENSION AND/OR IMPROVEMENT AND/OR RECONSTRUCTION AND/OR REHABILITATION AND/OR REPAIR AND/OR RENEWAL AND/ O RECOVERY AND/OR CONDITIONING AND/OR REMODELING AND/OR RECONSTRUCTION AND/OR IMPLEMENTATION AND/OR MAINTENANCE IN: SANITATION, EQUIPMENT, SCHOOLS, SCHOOLS, INSTITUTES, UNIVERSITIES, CLASSROOMS, PAVILIONS, SPORTS SITES, MULTI-SPORTS SITES, MEDICAL CENTERS, CENTERS HEALTH; ELECTRICAL, ELECTROMECHANICAL, MECHANICAL INFRASTRUCTURES; TRACKS, SIDEWALKS, GREEN AREAS, SARDINELS, FACADES, PASSAGES, STREETS, HIGHWAYS, FLEXIBLE OR RIGID PAVEMENT IN URBAN AND RURAL AREAS, CYCLE PATHS, TRAILS FOR CARS, ROADS, VEHICULAR AND PEDESTRIAN TRANSIT SERVICE, NEIGHBORHOOD ROADS, NEIGHBORHOOD ROADS, CONCRETE CHANNELS AND IRRIGATION, RIVER DEFENSES, DIKES, PROTECTION OF BASIC INFRASTRUCTURE, HYDRAULIC AND IRRIGATION, DRINKING WATER AND SEWERAGE, LATRINES, HOUSEHOLD WATER AND SEWAGE CONNECTIONS, WELLS, DAMS, HOSPITALS, IRRIGATION CANALS, FORESTATION, BRIDGES, ELECTRIFICATION, HYDROELECTRIC POWER PLANTS .",
          direccion: "CALLE ALICANTE 213, URB. JAVIER PRADO 5 TA ETAPA",
          direccion_ciudad: "LIMA - LIMA - SAN LUIS",
          direccion_pais: "PERÚ",
          file_logo: "",
          idtemitirfacturaa: 1,
          codigovalidez: null,
          fecvalidezdesde: "2023/08/02",
          fecvalidezhasta: "2026/07/02",
          fecprimeraexpedicion: "2024/07/02",
          fecsegundaexpedicion: "2025/07/02",
          fecsegundafechavigilancia: null,
          fecrecertificacionvence: null,
          fecproblemainicial: null,
          fecasunto: null,
          feccaducidad: null,
          idtfirma: null,
          cliente_fontsize: 17,
          clientedireccion_fontsize: 10,
          alcance_fontsize: 8,
          tracking_direccion: null,
          tracking_contacto: null,
          tracking_telefono: null,
          tracking_referencia: null,
          tracking_numero: null,
          flaestadoplaneacion: 5,
          cobranza_abono: 0,
          cobranza_saldo: 0,
          flaestadocobranza: 0,
          file_informe1: "",
          informe_observacion1: "",
          informe_respuesta1: "",
          file_informe2: "",
          informe_observacion2: "",
          informe_respuesta2: "",
          flaestadoauditoria: 1,
          file_diseno1: null,
          file_diseno2: null,
          certificado_email: null,
          certificado_flaestado: 1,
          certificado_flasuspender: 0,
          usuregistro: null,
          fecregistro: null,
          usumodifica: null,
          fecmodifica: "2023-08-15T21:32:51.427",
          mce_ctPartner: {
            "idtpartner": 0,
            "idtsucursal": 0,
            "despartner": "SISTEMACERTS /Diomedes Maza",
            "email": "diomedes.maza@ll-c.pe",
            "idttipoidentidad": null,
            "nombrecompleto": null,
            "numeroidentificacionfiscal": null,
            "direccion": null,
            "idtubigeo": 0,
            "flaestado": 0,
            "usuregistro": null,
            "fecregistro": null,
            "usumodifica": null,
            "fecmodifica": null,
            "mce_geUbigeo": null
          },
          "mce_coCliente": {
            "idtcliente": 0,
            "idtpartner": 0,
            "nombrecompleto": "VACAS INGENIEROS EL TORO S.A.C",
            "nombrecompletoingles": null,
            "nombre": null,
            "numeroregistro": null,
            "numeroidentificacionfiscal": "20494101662",
            "web": null,
            "calle": "AL.ALICANTE NRO. 213 URB. JAVIER PRADO 5TA ETAPA LIMA - LIMA - SAN LUIS",
            "calleingles": null,
            "ciudad": "",
            "codigopostal": null,
            "ciudadingles": null,
            "idtubigeo": null,
            "pais": null,
            "contacto": null,
            "email": null,
            "telefono1": null,
            "telefono2": null,
            "telefono3": null,
            "representantelegal": null,
            "posicioncontacto": null,
            "emailcontacto": null,
            "logo": null,
            "flaproforma": 0,
            "flaestado": 0,
            "usuregistro": null,
            "fecregistro": "0001-01-01T00:00:00",
            "usumodifica": null,
            "fecmodifica": null,
            "mce_ctPartner": null,
            "mce_geTipoIdentidad": null,
            "mce_geUbigeo": null
          },
          "mce_coTipoServicio": null,
          "mce_geTipoMoneda": {
            "idttipomoneda": 0,
            "destipomoneda": "PEN",
            "abreviatura": null,
            "sunat": null,
            "flaestado": 0,
            "usuregistro": null,
            "fecregistro": null,
            "usumodifica": null,
            "fecmodifica": null
          },
          "mce_ctUsuario": null,
          "mce_coAuditor": null,
          "mce_coFirma": null,
          "mcl_coOfertaStandar": null,
          "mcl_coOfertaDiasAuditorias": null,
          "mcl_coOfertaRequisitoDetalle": null,
          "mcl_coOfertaPago": null,
          "mcl_coOfertaPago_Detraccion": null,
          "searchIdtstandar": 0,
          "searchMes": 0,
          "searchPeriodo": 0,
          "searchIdttipoauditoria": 0,
          "searchEjecutivoComercial": 0,
          "searchDepartamento": null,
          "standars": null,
          "tiposervicios": null
        },
        "mce_coStandar": {
          "idtstandar": 0,
          "idttiponacegrupo": 0,
          "desstandar": "ISO 45001:2018",
          "descripcion": "Sistema de Gestión de la Seguridad y la Salud en el Trabajo",
          "descripcionen": "Occupational Health and Safety Management  System ",
          "reconocimientointernacional": "IAF Forum Internacional de Acreditacion https://www.iaf.nu",
          "flaorderby": 0,
          "flaestado": 0,
          "usuregistro": null,
          "fecregistro": null,
          "usumodifica": null,
          "fecmodifica": null
        },
        "mce_coTipoNace": {
          "idttiponace": 0,
          "codigo": "42",
          "idttiponacegrupo": 0,
          "destiponace": null,
          "flaestado": 0,
          "usuregistro": null,
          "fecregistro": null,
          "usumodifica": null,
          "fecmodifica": null,
          "mce_coStandar": null
        },
        "mce_coTipoAcreditacion": {
          "idttipoacreditacion": 0,
          "destipoacreditacion": "IAS",
          "flaestado": 0,
          "usuregistro": null,
          "fecregistro": null,
          "usumodifica": null,
          "fecmodifica": null
        },
        "mce_coTipoAuditoria": {
          "idttipoauditoria": 0,
          "destipoauditoria": "Auditoria Certificacion Inicial",
          "flaestado": 0,
          "usuregistro": null,
          "fecregistro": null,
          "usumodifica": null,
          "fecmodifica": null
        },
        "mce_coFirma": {
          "idtfirma": 0,
          "desfirma": null,
          "archivo": "certificado-firma-aprobado-1p.png",
          "flaestado": 0,
          "usuregistro": null,
          "fecregistro": null,
          "usumodifica": null,
          "fecmodifica": null
        },
        "mcl_coTipoNace": null,
        "mcl_coOfertaStandarNace": null,
        "mcl_coOfertaStandarPregunta": null,
        "mcl_coTipoAcreditacionStandar": null,
        "mcl_coTipoAuditoria": null,
        "mcl_coModuloEvaluacion": null
      }
  ]


router.get('/', (req, res) => {
    res.json('Node JS API')
});

router.get('/api/students', (req, res) => {
    res.json(students);
});

router.get('/api/students/:id', (req, res) => {
    const student = students.find(c => c.id === parseInt(req.params.id));
    if (!student) return res.status(404).send('Estudiante no encontrado');
    else res.json(student);
});

router.get('/api/coOfertaStandar/ObtenerCertificado/:idtofertastandar', (req, res) => {
    res.header('Access-Control-Allow-Origin', '*');

    const student = certificado.find(c => c.idtofertastandar === parseInt(req.params.idtofertastandar));
    if (!student) return res.status(404).send('Codigo no encontrado');
    else res.json([student]);
});

router.get('/api/coOfertaStandar/ObtenerPorCodigoValidez/:codigovalidez', (req, res) => {
    res.header('Access-Control-Allow-Origin', '*');

    const student = students.find(c => c.codigovalidez === String(req.params.codigovalidez).replaceAll("*", "/"));
    if (!student) return res.status(404).send('Codigo no encontrado');
    else res.json([student]);
});


// router.get('/api/coOfertaStandar/FormatoPDF/:idtofertastandar/0/S', (req, res) => {
//     res.header('Access-Control-Allow-Origin', '*');

//     const student = certificado.find(c => c.idtofertastandar === parseInt(req.params.idtofertastandar));
//     const file = `${__dirname}/upload/11394.pdf`;
//     res.download(file); // Set disposition and send it.
//   });



router.get('/api/coOfertaStandar/FormatoPDF/:fileName/0/S', (req, res) => {
    res.header('Access-Control-Allow-Origin', '*');
    
    const fileName = req.params.fileName;
    const filePath = `./pdfs/${fileName}.pdf`; // Ruta de la carpeta donde se almacenan los archivos PDF
  
    // Verifica si el archivo existe antes de descargarlo
    if (fs.existsSync(filePath)) {
      res.download(filePath, (err) => {
        if (err) {
          console.error(`Error al descargar el archivo ${fileName}: ${err}`);
          res.status(500).send('Error al descargar el archivo');
        } else {
          console.log(`Archivo ${fileName} descargado con éxito.`);
        }
      });
    } else {
      res.status(404).send('El archivo no existe.');
    }
  });


module.exports = router;